name: ESLint Action

on:
  push:
    branches:
      - main-2020
      - main-2021
  pull_request:
    branches:
      - main-2020
      - main-2021

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16']

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      # installs dependencies
    - run: npm ci --force

      # run lint script
    - name: Run ESLint
      run: npm run lint
