name: Unit Test Action

on:
  push:
    branches:
      - main-2020
      - main-2021
  pull_request:
    branches:
      - main-2020
      - main-2021

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - '16'

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      # installs dependencies
    - run: npm ci
      # make sure we can build with tsc
    - run: npm run build
      # run tests
    - name: Run jest unit tests
      run: npm run test:report
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage
        verbose: true
